# Generated by Django 5.2.7 on 2025-11-16 09:44

import django.core.validators
import django_mongodb_backend.fields
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this customer belongs to.', related_name='customer_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this customer.', related_name='customer_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='StoreOwner',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تماس باید با 09 شروع شود و 11 رقم باشد', regex='^09\\d{9}$')])),
                ('post_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='کد پستی باید ۱۰ رقم باشد', regex='^\\d{10}$')])),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('image_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('image_size', models.IntegerField(blank=True, null=True)),
                ('image_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('banned', 'banned')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(help_text='نام فروشگاه', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('seller_address', models.TextField(blank=True, default='', help_text='آدرس فروشنده')),
                ('seller_license_id', models.CharField(blank=True, help_text='شناسه مجوز فروشنده', max_length=100, null=True)),
                ('seller_bio', models.TextField(blank=True, default='', help_text='بیوگرافی فروشنده')),
                ('seller_social_links', models.JSONField(blank=True, default=dict, help_text='لینک\u200cهای شبکه\u200cهای اجتماعی')),
                ('seller_join_date', models.DateTimeField(auto_now_add=True, help_text='تاریخ عضویت فروشنده')),
                ('seller_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='approved', help_text='وضعیت فروشنده', max_length=20)),
                ('seller_rating', models.JSONField(blank=True, default=dict, help_text='امتیاز فروشنده (average, count)')),
                ('last_login', models.DateTimeField(blank=True, help_text='آخرین ورود', null=True)),
                ('store_logo_data', models.BinaryField(blank=True, null=True)),
                ('store_logo_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('store_logo_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('store_logo_size', models.IntegerField(blank=True, null=True)),
                ('store_logo_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('store_domain', models.CharField(blank=True, help_text='دامنه فروشگاه', max_length=255, null=True)),
                ('store_description', models.TextField(blank=True, default='', help_text='توضیحات فروشگاه')),
                ('store_type', models.CharField(choices=[('single-vendor', 'Single Vendor'), ('multi-vendor', 'Multi Vendor')], default='single-vendor', help_text='نوع فروشگاه', max_length=20)),
                ('store_established_at', models.DateField(blank=True, help_text='تاریخ تاسیس فروشگاه', null=True)),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='ساعات کاری')),
                ('supported_languages', models.JSONField(blank=True, default=list, help_text='زبان\u200cهای پشتیبانی شده')),
                ('supported_currencies', models.JSONField(blank=True, default=list, help_text='واحدهای پولی پشتیبانی شده')),
                ('terms_and_conditions', models.TextField(blank=True, default='', help_text='شرایط و ضوابط')),
                ('privacy_policy', models.TextField(blank=True, default='', help_text='سیاست حفظ حریم خصوصی')),
                ('store_rating', models.JSONField(blank=True, default=dict, help_text='امتیاز فروشگاه (average, count)')),
                ('active_products_count', models.IntegerField(default=0, help_text='تعداد محصولات فعال')),
                ('total_sales', models.IntegerField(default=0, help_text='تعداد کل فروش')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='درآمد کل', max_digits=15)),
                ('payment_settings', models.JSONField(blank=True, default=dict, help_text='تنظیمات پرداخت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this store owner belongs to.', related_name='storeowner_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this store owner.', related_name='storeowner_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Store Owner',
                'verbose_name_plural': 'Store Owners',
                'indexes': [models.Index(fields=['phone'], name='marketplace_phone_0a3ff5_idx'), models.Index(fields=['email'], name='marketplace_email_acdc7f_idx'), models.Index(fields=['store_name'], name='marketplace_store_n_7a17cd_idx'), models.Index(fields=['seller_status'], name='marketplace_seller__557b87_idx'), models.Index(fields=['store_type'], name='marketplace_store_t_dc6111_idx')],
            },
            managers=[
                ('objects', marketplace.models.StoreOwnerManager()),
            ],
        ),
    ]
